server:
  port: 8771
#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: gateway-service
#          uri: https://www.baidu.com/
#          predicates:
#            - Path=/hello
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    # 注意格式的缩进
    fetch-registry: false
    service-url:
        defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
hunter:
  config:
    enable: true
    hunterinfo:
      hunter-server-name: Hunter2